/**
 * Generated from `DEVICES` in presets/index.ts — do not hand-edit.
 * Regenerate with `pnpm --filter @devicekit/devices generate:device-names`.
 */
export const DEVICE_NAMES = {
  iPhone_SE: 'iPhone SE',
  iPhone_XR: 'iPhone XR',
  iPhone_12_Pro: 'iPhone 12 Pro',
  iPhone_14: 'iPhone 14',
  iPhone_14_Plus: 'iPhone 14 Plus',
  iPhone_14_Pro: 'iPhone 14 Pro',
  iPhone_14_Pro_Max: 'iPhone 14 Pro Max',
  iPhone_15: 'iPhone 15',
  iPhone_15_Plus: 'iPhone 15 Plus',
  iPhone_15_Pro: 'iPhone 15 Pro',
  iPhone_15_Pro_Max: 'iPhone 15 Pro Max',
  iPhone_16e: 'iPhone 16e',
  iPhone_16: 'iPhone 16',
  iPhone_16_Plus: 'iPhone 16 Plus',
  iPhone_16_Pro: 'iPhone 16 Pro',
  iPhone_16_Pro_Max: 'iPhone 16 Pro Max',
  iPad_Mini: 'iPad Mini',
  iPad_Pro_13: 'iPad Pro 13',
  iPhone_5: 'iPhone 5',
  iPhone_6_7_8: 'iPhone 6/7/8',
  iPhone_6_7_8_Plus: 'iPhone 6/7/8 Plus',
  iPhone_X: 'iPhone X',
  iPhone_XS_Max: 'iPhone XS Max',
  iPhone_12_13_mini: 'iPhone 12/13 mini',
  iPhone_12_13_Pro: 'iPhone 12/13 (Pro)',
  iPhone_12_13_Pro_Max: 'iPhone 12/13 Pro Max',
  iPad: 'iPad',
  iPad_Pro_10_5_inch: 'iPad Pro 10.5-inch',
  iPad_Pro_12_9_inch: 'iPad Pro 12.9-inch',
  iPad_gen_5: 'iPad (gen 5)',
  iPad_gen_6: 'iPad (gen 6)',
  iPad_gen_7: 'iPad (gen 7)',
  iPad_gen_11: 'iPad (gen 11)',
  iPad_Pro_11: 'iPad Pro 11',
  iPhone_6: 'iPhone 6',
  iPhone_6_Plus: 'iPhone 6 Plus',
  iPhone_7: 'iPhone 7',
  iPhone_7_Plus: 'iPhone 7 Plus',
  iPhone_8: 'iPhone 8',
  iPhone_8_Plus: 'iPhone 8 Plus',
  iPhone_SE_3rd_gen: 'iPhone SE (3rd gen)',
  iPhone_11: 'iPhone 11',
  iPhone_11_Pro: 'iPhone 11 Pro',
  iPhone_11_Pro_Max: 'iPhone 11 Pro Max',
  iPhone_12: 'iPhone 12',
  iPhone_12_Pro_Max: 'iPhone 12 Pro Max',
  iPhone_12_Mini: 'iPhone 12 Mini',
  iPhone_13: 'iPhone 13',
  iPhone_13_Pro: 'iPhone 13 Pro',
  iPhone_13_Pro_Max: 'iPhone 13 Pro Max',
  iPhone_13_Mini: 'iPhone 13 Mini',
  iPhone_17: 'iPhone 17',
  iPhone_Air: 'iPhone Air',
  iPhone_17_Pro: 'iPhone 17 Pro',
  iPhone_17_Pro_Max: 'iPhone 17 Pro Max',
  iPhone_17e: 'iPhone 17e',
  iPhone_4: 'iPhone 4',
  iPhone_5_SE: 'iPhone 5/SE',
  iPad_Air: 'iPad Air',
  iPad_Pro: 'iPad Pro',
  iPhone_17_Air: 'iPhone 17 Air',
  iPad_Pro_M4: 'iPad Pro M4',
  iPad_Air_M2: 'iPad Air M2',
  Pixel_7: 'Pixel 7',
  Pixel_8: 'Pixel 8',
  Pixel_8_Pro: 'Pixel 8 Pro',
  Pixel_8a: 'Pixel 8a',
  Pixel_9: 'Pixel 9',
  Pixel_9_Pro: 'Pixel 9 Pro',
  Pixel_9_Pro_XL: 'Pixel 9 Pro XL',
  Pixel_10: 'Pixel 10',
  Samsung_Galaxy_S8: 'Samsung Galaxy S8+',
  Samsung_Galaxy_S20_Ultra: 'Samsung Galaxy S20 Ultra',
  Surface_Duo: 'Surface Duo',
  Surface_Duo_inner: 'Surface Duo (inner)',
  Samsung_Galaxy_A55: 'Samsung Galaxy A55',
  Pixel_9_Pro_Fold: 'Pixel 9 Pro Fold',
  Pixel_9_Pro_Fold_inner: 'Pixel 9 Pro Fold (inner)',
  Galaxy_Z_Fold_6: 'Galaxy Z Fold 6',
  Galaxy_Z_Fold_6_inner: 'Galaxy Z Fold 6 (inner)',
  Galaxy_Z_Fold_5: 'Galaxy Z Fold 5',
  Galaxy_Z_Fold_5_inner: 'Galaxy Z Fold 5 (inner)',
  Samsung_Galaxy_A51_71: 'Samsung Galaxy A51/71',
  Galaxy_Tab_S4: 'Galaxy Tab S4',
  Moto_G4: 'Moto G4',
  Moto_G_Power: 'Moto G Power',
  Nexus_5: 'Nexus 5',
  Nexus_5X: 'Nexus 5X',
  Nexus_6: 'Nexus 6',
  Galaxy_Note_3: 'Galaxy Note 3',
  Galaxy_Note_II: 'Galaxy Note II',
  Galaxy_S_III: 'Galaxy S III',
  Galaxy_S5: 'Galaxy S5',
  Galaxy_S9: 'Galaxy S9+',
  Galaxy_S24: 'Galaxy S24',
  Galaxy_Tab_S9: 'Galaxy Tab S9',
  Galaxy_Z_Fold_6_Cover: 'Galaxy Z Fold 6 Cover',
  Galaxy_Z_Fold_7: 'Galaxy Z Fold 7',
  Galaxy_Z_Fold_7_Cover: 'Galaxy Z Fold 7 Cover',
  Galaxy_Z_Flip_6: 'Galaxy Z Flip 6',
  Galaxy_Z_Flip_6_Cover: 'Galaxy Z Flip 6 Cover',
  Galaxy_Z_Flip_7: 'Galaxy Z Flip 7',
  Galaxy_Z_Flip_7_Cover: 'Galaxy Z Flip 7 Cover',
  LG_Optimus_L70: 'LG Optimus L70',
  Nexus_10: 'Nexus 10',
  Nexus_4: 'Nexus 4',
  Nexus_6P: 'Nexus 6P',
  Nexus_7: 'Nexus 7',
  Pixel_2: 'Pixel 2',
  Pixel_2_XL: 'Pixel 2 XL',
  Pixel_3: 'Pixel 3',
  Pixel_4: 'Pixel 4',
  Pixel_4a_5G: 'Pixel 4a (5G)',
  Pixel_5: 'Pixel 5',
  Pixel_6: 'Pixel 6',
  Pixel_6_Pro: 'Pixel 6 Pro',
  Pixel_6a: 'Pixel 6a',
  Pixel_7_Pro: 'Pixel 7 Pro',
  Pixel_7a: 'Pixel 7a',
  Pixel_10_Pro: 'Pixel 10 Pro',
  Pixel_10_Pro_XL: 'Pixel 10 Pro XL',
  Pixel_3_XL: 'Pixel 3 XL',
  Pixel_Fold: 'Pixel Fold',
  Pixel_Tablet: 'Pixel Tablet',
  Pixel_9a: 'Pixel 9a',
  Galaxy_Fold: 'Galaxy Fold',
  Galaxy_S21: 'Galaxy S21',
  Galaxy_S21_Plus: 'Galaxy S21 Plus',
  Galaxy_S21_Ultra: 'Galaxy S21 Ultra',
  Galaxy_S20: 'Galaxy S20',
  Galaxy_S20_Plus: 'Galaxy S20 Plus',
  Samsung_S21_FE: 'Samsung S21 FE',
  Galaxy_Fold3_Folded: 'Galaxy Fold3 (Folded)',
  Galaxy_Fold3_Unfolded: 'Galaxy Fold3 (Unfolded)',
  Galaxy_S22: 'Galaxy S22',
  Galaxy_S22_Plus: 'Galaxy S22 Plus',
  Galaxy_S22_Ultra: 'Galaxy S22 Ultra',
  Galaxy_S23: 'Galaxy S23',
  Galaxy_S23_Plus: 'Galaxy S23 Plus',
  Galaxy_S23_Ultra: 'Galaxy S23 Ultra',
  Galaxy_S24_Plus: 'Galaxy S24 Plus',
  Galaxy_S24_Ultra: 'Galaxy S24 Ultra',
  Galaxy_Z_Flip_5: 'Galaxy Z Flip 5',
  Galaxy_Z_Fold_4: 'Galaxy Z Fold 4',
  OnePlus_12: 'OnePlus 12',
  Nothing_Phone_2: 'Nothing Phone 2',
  Xiaomi_14: 'Xiaomi 14',
  Motorola_Razr: 'Motorola Razr+',
  OnePlus_Open: 'OnePlus Open',
  HUAWEI_Mate_80: 'HUAWEI Mate 80',
  HUAWEI_Mate_70: 'HUAWEI Mate 70',
  HUAWEI_Mate_70_Pro: 'HUAWEI Mate 70 Pro',
  HUAWEI_Mate_60: 'HUAWEI Mate 60',
  HUAWEI_Mate_60_Pro: 'HUAWEI Mate 60 Pro',
  HUAWEI_Pura_80_Pro: 'HUAWEI Pura 80 Pro',
  HUAWEI_nova_14_Ultra: 'HUAWEI nova 14 Ultra',
  HUAWEI_Pura_X_inner: 'HUAWEI Pura X (inner)',
  HUAWEI_Pura_X_outer: 'HUAWEI Pura X (outer)',
  HUAWEI_Mate_X6_inner: 'HUAWEI Mate X6 (inner)',
  HUAWEI_Mate_X6_outer: 'HUAWEI Mate X6 (outer)',
  HUAWEI_Pura_70: 'HUAWEI Pura 70',
  HUAWEI_Pura_70_Pro: 'HUAWEI Pura 70 Pro',
  HUAWEI_Mate_X5_inner: 'HUAWEI Mate X5 (inner)',
  HUAWEI_Mate_X5_outer: 'HUAWEI Mate X5 (outer)',
  HUAWEI_Pocket_2: 'HUAWEI Pocket 2',
  HUAWEI_nova_13: 'HUAWEI nova 13',
  HUAWEI_nova_13_Pro: 'HUAWEI nova 13 Pro',
  HUAWEI_nova_12: 'HUAWEI nova 12',
  HUAWEI_nova_12_Pro: 'HUAWEI nova 12 Pro',
  HUAWEI_Pura_X_Max_outer: 'HUAWEI Pura X Max (outer)',
  HUAWEI_Pura_X_Max_inner: 'HUAWEI Pura X Max (inner)',
} as const
